name: Deploy to Krystal Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.14.0'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Debug Secrets
        run: |
          echo "HOST: ${{ secrets.SSH_HOST }}"
          echo "USERNAME: ${{ nexttemp.SSH_USERNAME }}"
          # Print the length of the private key to ensure it's being set (DO NOT print the key itself)
          echo "Private Key Length: ${#secrets.SSH_PRIVATE_KEY}"
          echo "Debugging completed."
          echo "Hello Pa g!"

      - name: Deploy to Krystal Hosting
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Deploying to Krystal Hosting..."
            cd .
            echo "Current directory contents:"
            ls -la
            echo "Removing old files..."
            rm -rf *
            echo "Current directory contents after removal:"
            ls -la
            echo "Deploying new files..."
            tar czf - . | ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'tar xzf - -C /home/wecarhir/temp.litpaint.com/'
            echo "Deployment completed."
