name: Check Secrets

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Secrets
        run: |
          echo "HOST: ${{ secrets.SSH_HOST }}"
          echo "USERNAME: ${{ secrets.SSH_USERNAME }}"
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "Private Key is not set."
          else
            echo "Private Key is set."
          fi
